export const TeacherDetailFields = [
    {
      type: 'text',
      name: 'user_id',
      label: 'User ID',
      placeholder: 'Enter User ID (unique)',
      required: true,
      maxLength: '30',
    },
    {
      type: 'text',
      name: 'firstName',
      label: 'First Name',
      placeholder: 'Enter First Name',
      required: true,
      maxLength: '30',
    },    
    {
      type: 'text',
      name: 'lastName',
      label: 'Last Name',
      placeholder: 'Enter Last Name',
      required: true,
      maxLength: '30',
    },
    {
      type: 'text',
      name: 'displayName',
      label: 'Display Name',
      placeholder: 'Optional Display Name',
      required: false,
      maxLength: '30',
    },     
    {
      type: 'email',
      name: 'emailId',
      label: 'Email',
      placeholder: 'Enter Email ID',
      required: true,
      maxLength: '60',
    },
    {
      type: 'email',
      name: 'alternateEmailID',
      label: 'Alternate Email',
      placeholder: 'Enter Alternate Email ID',
      required: false,
      maxLength: '60',
    },
    {
      type: 'date',
      name: 'dob',
      label: 'Date of Birth',
      placeholder: 'Select DOB',
      required: true,
    },
    {
        type: 'date',
        name: 'joiningDate',
        label: 'Joining Date',
        placeholder: 'Select Joining Date',
        required: true,
      },
    {
      type: 'dropdown',
      name: 'gender',
      label: 'Gender',
      placeholder: 'Select Gender',
      required: true,
      options: [
        { label: 'Male', value: 'Male' },
        { label: 'Female', value: 'Female' },
        { label: 'Other', value: 'Other' },
      ],
    },
    {
      type: 'text',
      name: 'phoneNumber',
      label: 'Phone Number',
      placeholder: 'Enter Contact Number',
      required: true,
      maxLength: '15',
    },    
    {
      type: 'text',
      name: 'password',
      label: 'Password',
      placeholder: 'Enter Password',
      required: true,
      maxLength: '50',
    },
    {
      type: 'text',
      name: 'confirmpassword',
      label: 'Confirm Password',
      placeholder: 'Confirm Password',
      required: false,
      maxLength: '50',
    },
    {
      type: 'text',
      name: 'bloodGroup',
      label: 'Blood Group',
      placeholder: 'e.g. A+, B-, O+',
      required: false,
      maxLength: '5',
    },
    {
      type: 'text',
      name: 'state',
      label: 'State',
      placeholder: 'Enter State',
      required: true,
      maxLength: '50',
    },
    {
      type: 'text',
      name: 'city',
      label: 'City',
      placeholder: 'Enter City',
      required: false,
      maxLength: '50',
    },
    {
      type: 'text',
      name: 'pinCode',
      label: 'Pin Code',
      placeholder: 'Enter Pin Code',
      required: true,
      maxLength: '10',
    },
    {
      type: 'textarea',
      name: 'address',
      label: 'Address',
      placeholder: 'Enter Residential Address',
      required: true,
      maxLength: '300',
      rows: 3,
    },
    {
      type: 'dropdown',
      name: 'department',
      label: 'Department',
      placeholder: 'Select Department',
      required: false,
      options: [], // To be populated dynamically
    },
    {
      type: 'dropdown',
      name: 'roles',
      label: 'Role',
      placeholder: 'Select Role',
      required: true,
      options: [
        { label: 'Teacher', value: 'Teacher' },       
      ],
    },
    {
        type: 'multiselect',
        name: 'education',
        label: 'Education',
        placeholder: 'Enter Education Details',
        required: true,
        options: [
          { label: 'UG', value: 'UG' },
          { label: 'PG', value: 'PG' },
          { label: 'Research', value: 'Research' },
          { label: 'Phd', value: 'Phd' },
          { label: '10', value: '10' },
          { label: '12', value: '12' },
          { label: 'Others', value: 'Others' },
        ],
        maxLength: '100',
      },
      {
        type: 'text',
        name: 'designation',
        label: 'Designation',
        placeholder: 'e.g. Senior Proffessor, Junior Proffessor',
        required: true,
        maxLength: '50',
      },
    {
      type: 'dropdown',
      name: 'isActive',
      label: 'Status',
      placeholder: 'Select Status',
      required: true,
      options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ],
    }, 
    {
      type: 'text',
      name: 'experience',
      label: 'Experience',
      placeholder: 'e.g. 5 years in admin',
      required: false,
      maxLength: '100',
    }, 
    {
      type: 'attachment',
      name: 'experienceDocument',
      label: 'Supporting Experience Documents (PDFs)',
      placeholder: 'Upload Supporting Experience Documents',
      required: false,
      multiple: true,
      accept: 'application/pdf',
    }, 
    {
      type: 'attachment',
      name: 'educationDocument',
      label: 'Supporting Education Documents (PDFs)',
      placeholder: 'Upload Supporting Education Documents',
      required: false,
      multiple: true,
      accept: 'application/pdf',
    }, 
    {
      type: 'attachment',
      name: 'certificationDocument',
      label: 'Supporting Certification Documents (PDFs)',
      placeholder: 'Upload Supporting Certification Documents',
      required: false,
      multiple: true,
      accept: 'application/pdf',
    },  
    {
      type: 'attachment',
      name: 'uploadPhoto',
      label: 'Upload Photo',
      placeholder: 'Upload Staff Photo',
      required: false,
      multiple: false,
      accept: 'image/*',
    },
  ];
  