export const DesignationDetailFields = [
  {
    type: 'text',
    name: 'designationName',
    label: 'Designation Name',
    placeholder: 'e.g. Assistant Professor',
    maxLength: '50',
    required: true,
  },
  {
    type: 'text',
    name: 'designationCode',
    label: 'Designation Code',
    placeholder: 'e.g. AP01, HOD02',
    maxLength: '15',
    required: true,
  },
  {
    type: 'dropdown',
    name: 'applicableRoles',
    label: 'Applicable For',
    placeholder: 'Select Role Types',
    required: true,
    options: [
      { label: 'Staff', value: 'Staff' },
      { label: 'Teacher', value: 'Teacher' },
      { label: 'HOD', value: 'HOD' },
      { label: 'Admin', value: 'Admin' },
      { label: 'Professor', value: 'Professor' },
      { label: 'Associate Professor', value: 'Associate Professor' },
      { label: 'Finance', value: 'Finance' },
      { label: 'Vice Principal', value: 'Vice Principal' },
      { label: 'Principal', value: 'Principal' },
    ],
  },
  {
    type: 'dropdown',
    name: 'status',
    label: 'Status',
    placeholder: 'Select Status',
    options: [
      { label: 'Active', value: 'active' },
      { label: 'Inactive', value: 'inactive' },
    ],
    required: true,
  },
  {
    type: 'textarea',
    name: 'description',
    label: 'Description / Notes',
    placeholder: 'Optional details about the designation',
    maxLength: '250',
    rows: 3,
    required: false,
  },
];
