export const subMenuConfig = [  
  {
    id: 'students',
    label: 'All Students',
    path: 'all/students',
    requiredRole: ['admin', 'teacher', 'staff'],
  },
  {
    id: 'students',
    label: 'Add Student',
    path: 'add/students',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'students',
    label: 'Edit Student',
    path: 'edit/students',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'students',
    label: 'About Student',
    path: 'about/students',
    requiredRole: ['admin', 'teacher', 'staff'],
  },
  {
    id: 'students',
    label: 'Student Attendance',
    path: 'attendance/students',
    requiredRole: ['admin', 'teacher', 'staff'],
  }, 
  {
    id: 'teachers',
    label: 'All Teachers',
    path: 'all/teachers',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'teachers',
    label: 'Add Teacher',
    path: 'add/teachers',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'teachers',
    label: 'Edit Teacher',
    path: 'edit/teachers',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'teachers',
    label: 'About Teacher',
    path: 'about/teachers',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'staff',
    label: 'All Staff',
    path: 'all/staff',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'staff',
    label: 'Add Staff',
    path: 'add/staff',
    requiredRole: ['admin'],
  },
  {
    id: 'staff',
    label: 'Edit Staff',
    path: 'edit/staff',
    requiredRole: ['admin'],
  },
  {
    id: 'staff',
    label: 'About Staff',
    path: 'about/staff',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'classes',
    label: 'All Classes',
    path: 'all/classes',
    requiredRole: ['admin', 'teacher', 'staff', 'student'],
  },
  {
    id: 'classes',
    label: 'Add Class',
    path: 'add/classes',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'classes',
    label: 'Edit Class',
    path: 'edit/classes',
    requiredRole: ['admin','staff'],
  },  
  {
    id: 'timetable',
    label: 'Add Timetable',
    path: 'add/timetable',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'timetable',
    label: 'Edit Timetable',
    path: 'edit/timetable',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'timetable',
    label: 'View Timetable',
    path: 'view/timetable',
    requiredRole: ['admin', 'teacher', 'staff', 'student'],
  },
  {
    id: 'courses',
    label: 'All Courses',
    path: 'all/courses',
    requiredRole: ['admin', 'teacher', 'staff', 'student'],
  },  
  {
    id: 'courses',
    label: 'Add Course',
    path: 'add/courses',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'courses',
    label: 'Edit Course',
    path: 'edit/courses',
    requiredRole: ['admin','staff'],
  }, 
  {
    id: 'syllabus',
    label: 'View Syllabus',
    path: 'view/syllabus',
    requiredRole: ['admin', 'teacher', 'staff', 'student'],
  },
  {
    id: 'syllabus',
    label: 'Add Syllabus',
    path: 'add/syllabus',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'syllabus',
    label: 'Edit Syllabus',
    path: 'edit/syllabus',
    requiredRole: ['admin','staff'],
  },  
  {
    id: 'fees',
    label: 'Add Fees Record',
    path: 'add/fees',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'fees',
    label: 'Edit Fees Record',
    path: 'edit/fees',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'fees',
    label: 'Fees Payment History',
    path: 'history/fees',
    requiredRole: ['admin', 'staff', 'student'],
  },
  {
    id: 'fees',
    label: 'Generate Fees Receipt',
    path: 'receipt/fees',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'library',
    label: 'All Books',
    path: 'all/library',
    requiredRole: ['admin', 'teacher', 'staff', 'student'],
  }, 
  {
    id: 'library',
    label: 'Add New Book',
    path: 'add/library',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'library',
    label: 'Edit Book Info',
    path: 'edit/library',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'library',
    label: 'Issue Book',
    path: 'issue/library',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'library',
    label: 'Return Book',
    path: 'return/library',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'library',
    label: 'My Issued Books',
    path: 'my/library',
    requiredRole: ['teacher', 'student'],
  },
  {
    id: 'departments',
    label: 'All Departments',
    path: 'all/departments',
    requiredRole: ['admin', 'staff', 'teacher'],
  },
  {
    id: 'departments',
    label: 'Add Department',
    path: 'add/departments',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'departments',
    label: 'Edit Department',
    path: 'edit/departments',
    requiredRole: ['admin','staff'],
  },
  {
    id: 'designation',
    label: 'All Designations',
    path: 'all/designations',
    requiredRole: ['admin', 'staff','teacher'],
  },
  {
    id: 'designation',
    label: 'Add Designation',
    path: 'add/designations',
    requiredRole: ['admin'],
  },
  {
    id: 'designation',
    label: 'Edit Designation',
    path: 'edit/designations',
    requiredRole: ['admin'],
  },
  {
    id: 'attendance',
    label: 'All Attendance Records',
    path: 'all/attendance',
    requiredRole: ['admin', 'teacher', 'staff'],
  }, 
  {
    id: 'attendance',
    label: 'Edit Attendance',
    path: 'edit/attendance',
    requiredRole: ['admin', 'teacher'],
  },
  {
    id: 'attendance',
    label: 'My Attendance',
    path: 'my/attendance',
    requiredRole: ['student'],
  },
  {
    id: 'leaves',
    label: 'All Leave Requests',
    path: 'all/leaves',
    requiredRole: ['admin', 'staff', 'teacher'],
  },
  {
    id: 'leaves',
    label: 'Apply for Leave',
    path: 'apply/leaves',
    requiredRole: ['staff', 'teacher', 'student'],
  },
  {
    id: 'leaves',
    label: 'Approve/Reject Leave',
    path: 'manage/leaves',
    requiredRole: ['admin'],
  },
  {
    id: 'leaves',
    label: 'My Leave Status',
    path: 'my/leaves',
    requiredRole: ['staff', 'teacher', 'student'],
  },
  {
    id: 'holidays',
    label: 'All Holidays',
    path: 'all/holidays',
    requiredRole: ['admin', 'staff', 'teacher', 'student'],
  },
  {
    id: 'holidays',
    label: 'Add Holiday',
    path: 'add/holidays',
    requiredRole: ['admin'],
  },
  {
    id: 'holidays',
    label: 'Edit Holiday',
    path: 'edit/holidays',
    requiredRole: ['admin'],
  },
  {
    id: 'admission-inquiry',
    label: 'All Admission Inquiries',
    path: 'all/admission-inquiry',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'admission-inquiry',
    label: 'Add Admission Inquiry',
    path: 'add/admission-inquiry',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'admission-inquiry',
    label: 'Edit Admission Inquiry',
    path: 'edit/admission-inquiry',
    requiredRole: ['admin'],
  },
  {
    id: 'visitors-book',
    label: 'All Visitor Entries',
    path: 'all/visitors-book',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'visitors-book',
    label: 'Add Visitor Entry',
    path: 'add/visitors-book',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'visitors-book',
    label: 'Edit Visitor Entry',
    path: 'edit/visitors-book',
    requiredRole: ['admin'],
  },
  {
    id: 'complaints',
    label: 'All Complaints',
    path: 'all/complaints',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'complaints',
    label: 'Add Complaint',
    path: 'add/complaints',
    requiredRole: ['student', 'teacher', 'staff'],
  },
  {
    id: 'complaints',
    label: 'Resolve Complaint',
    path: 'resolve/complaints',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'feedback',
    label: 'Submit Feedback',
    path: 'submit/feedback',
    requiredRole: ['student'],
  },
  {
    id: 'feedback',
    label: 'All Feedback',
    path: 'all/feedback',
    requiredRole: ['admin','student'],
  },
  {
    id: 'notice-board',
    label: 'All Notices',
    path: 'all/notice-board',
    requiredRole: ['admin', 'staff', 'teacher', 'student'],
  },
  {
    id: 'notice-board',
    label: 'Add Notice',
    path: 'add/notice-board',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'notice-board',
    label: 'Edit Notice',
    path: 'edit/notice-board',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'events',
    label: 'All Events',
    path: 'all/events',
    requiredRole: ['admin', 'staff', 'teacher', 'student'],
  },
  {
    id: 'events',
    label: 'Add Event',
    path: 'add/events',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'events',
    label: 'Edit Event',
    path: 'edit/events',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'attendance-report',
    label: 'Attendance Report',
    path: 'report/attendance',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'class-report',
    label: 'Class Report',
    path: 'report/class',
    requiredRole: ['admin', 'staff', 'teacher'],
  },
  {
    id: 'student-report',
    label: 'Student Report',
    path: 'report/student',
    requiredRole: ['admin','student','teacher'],
  },
  {
    id: 'grade-report',
    label: 'Grade Report',
    path: 'report/grade',
    requiredRole: ['admin','student','teacher'],
  },
  {
    id: 'leave-report',
    label: 'Leave Report',
    path: 'report/leave',
    requiredRole: ['admin', 'staff'],
  },
  {
    id: 'fees-report',
    label: 'Fees Report',
    path: 'report/fees',
    requiredRole: ['admin', 'staff'],
  }
];